use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Parses the C header `src/html.h` generated by the frontend build and emits the raw
/// gzip payload as a binary file that `src/html.rs` embeds with `include_bytes!`.
///
/// Keeping the header as the single source of truth means the Rust build consumes exactly
/// the same frontend bundle as the C build, with no duplicated blob checked into the tree.
fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let header = manifest_dir.join("../src/html.h");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", header.display());
    println!("cargo:rerun-if-changed=build.rs");

    emit_version();

    let (gzip, uncompressed_size) = parse_header(&header);

    fs::write(out_dir.join("index.html.gz"), &gzip).expect("write index.html.gz");
    fs::write(
        out_dir.join("html_meta.rs"),
        format!(
            "pub const INDEX_HTML_SIZE: usize = {uncompressed_size};\n\
             pub const INDEX_HTML_GZIP_LEN: usize = {};\n",
            gzip.len()
        ),
    )
    .expect("write html_meta.rs");
}

/// Reproduces the CMake version scheme, `<crate version>-<short git hash>`, so that
/// `ttyd --version` matches what the C build reports for the same commit.
fn emit_version() {
    let base = env::var("CARGO_PKG_VERSION").unwrap();
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|h| !h.is_empty());

    let version = match hash {
        Some(h) => format!("{base}-{h}"),
        None => base,
    };
    println!("cargo:rustc-env=TTYD_VERSION={version}");
    println!("cargo:rerun-if-changed=../.git/HEAD");
}

fn parse_header(path: &Path) -> (Vec<u8>, usize) {
    let text =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let body_start = text
        .find('{')
        .unwrap_or_else(|| panic!("{}: no array literal found", path.display()));
    let body_end = text[body_start..]
        .find('}')
        .map(|i| body_start + i)
        .unwrap_or_else(|| panic!("{}: unterminated array literal", path.display()));

    let mut bytes = Vec::with_capacity(256 * 1024);
    for token in text[body_start + 1..body_end].split(',') {
        let token = token.trim();
        if token.is_empty() {
            continue;
        }
        let value = token
            .strip_prefix("0x")
            .or_else(|| token.strip_prefix("0X"))
            .map(|hex| u8::from_str_radix(hex, 16))
            .unwrap_or_else(|| token.parse::<u8>())
            .unwrap_or_else(|e| panic!("{}: bad byte {token:?}: {e}", path.display()));
        bytes.push(value);
    }

    let declared_len = scan_uint(&text, "index_html_len");
    let declared_size = scan_uint(&text, "index_html_size");

    assert_eq!(
        bytes.len(),
        declared_len,
        "{}: parsed {} bytes but index_html_len says {declared_len}",
        path.display(),
        bytes.len()
    );

    (bytes, declared_size)
}

fn scan_uint(text: &str, name: &str) -> usize {
    let idx = text
        .rfind(name)
        .unwrap_or_else(|| panic!("html.h: missing `{name}`"));
    let after_eq = text[idx..]
        .find('=')
        .map(|i| idx + i + 1)
        .unwrap_or_else(|| panic!("html.h: `{name}` has no value"));
    let digits: String = text[after_eq..]
        .chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits
        .parse()
        .unwrap_or_else(|e| panic!("html.h: `{name}` value {digits:?}: {e}"))
}
