use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Parses the C header `src/html.h` generated by the frontend build and emits the raw
/// gzip payload as a binary file that `src/html.rs` embeds with `include_bytes!`.
///
/// Keeping the header as the single source of truth means the Rust build consumes exactly
/// the same frontend bundle as the C build, with no duplicated blob checked into the tree.
fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let header = manifest_dir.join("../src/html.h");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", header.display());
    println!("cargo:rerun-if-changed=build.rs");

    emit_version();

    let (gzip, uncompressed_size) = parse_header(&header);

    fs::write(out_dir.join("index.html.gz"), &gzip).expect("write index.html.gz");
    fs::write(
        out_dir.join("html_meta.rs"),
        format!(
            "pub const INDEX_HTML_SIZE: usize = {uncompressed_size};\n\
             pub const INDEX_HTML_GZIP_LEN: usize = {};\n",
            gzip.len()
        ),
    )
    .expect("write html_meta.rs");
}

/// Reproduces the CMake version scheme, `<crate version>-<short git hash>`, so that
/// `ttyd --version` matches what the C build reports for the same commit.
fn emit_version() {
    let base = env::var("CARGO_PKG_VERSION").unwrap();
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|h| !h.is_empty());

    let version = match hash {
        Some(h) => format!("{base}-{h}"),
        None => base,
    };
    println!("cargo:rustc-env=TTYD_VERSION={version}");

    // `.git/HEAD` only changes when the *branch* changes — committing on the same branch
    // rewrites `.git/refs/heads/<branch>` instead. Watching HEAD alone leaves the version
    // stamp frozen at whatever commit the binary was first built from, which is worse than
    // having no stamp: it misidentifies a deployed binary.
    //
    // Both directories come from git rather than from assuming `../.git` is one. In a
    // worktree or a submodule `.git` is a *file* holding `gitdir: …`, so the assumed paths
    // would simply not exist and the stamp would go stale again — silently, which is the
    // failure mode this watching exists to prevent.
    let head_dir = git_path(&["rev-parse", "--absolute-git-dir"]);
    // A linked worktree has its own HEAD but shares refs/ and packed-refs with the main
    // checkout, so the two can be different directories.
    let refs_dir = git_path(&["rev-parse", "--path-format=absolute", "--git-common-dir"])
        .or_else(|| head_dir.clone());

    let Some(head_dir) = head_dir else { return };
    let Some(refs_dir) = refs_dir else { return };

    watch(&head_dir.join("HEAD"));
    if let Ok(head) = fs::read_to_string(head_dir.join("HEAD")) {
        if let Some(reference) = head.strip_prefix("ref:") {
            watch(&refs_dir.join(reference.trim()));
        }
    }
    // A ref that lives in `packed-refs` has no loose file to watch.
    watch(&refs_dir.join("packed-refs"));
}

/// Runs a `git rev-parse` that yields a path, returning `None` outside a repository or when
/// git is not installed — a source tarball builds fine, just without a hash in the version.
fn git_path(args: &[&str]) -> Option<PathBuf> {
    let output = std::process::Command::new("git").args(args).output().ok()?;
    if !output.status.success() {
        return None;
    }
    let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
    (!path.is_empty()).then(|| PathBuf::from(path))
}

/// Emits `rerun-if-changed` only for a path that exists. Naming a missing path makes cargo
/// re-run the build script on *every* build, which is a quiet waste rather than an error.
fn watch(path: &Path) {
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn parse_header(path: &Path) -> (Vec<u8>, usize) {
    let text =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

    let body_start = text
        .find('{')
        .unwrap_or_else(|| panic!("{}: no array literal found", path.display()));
    let body_end = text[body_start..]
        .find('}')
        .map(|i| body_start + i)
        .unwrap_or_else(|| panic!("{}: unterminated array literal", path.display()));

    let mut bytes = Vec::with_capacity(256 * 1024);
    for token in text[body_start + 1..body_end].split(',') {
        let token = token.trim();
        if token.is_empty() {
            continue;
        }
        let value = token
            .strip_prefix("0x")
            .or_else(|| token.strip_prefix("0X"))
            .map(|hex| u8::from_str_radix(hex, 16))
            .unwrap_or_else(|| token.parse::<u8>())
            .unwrap_or_else(|e| panic!("{}: bad byte {token:?}: {e}", path.display()));
        bytes.push(value);
    }

    let declared_len = scan_uint(&text, "index_html_len");
    let declared_size = scan_uint(&text, "index_html_size");

    assert_eq!(
        bytes.len(),
        declared_len,
        "{}: parsed {} bytes but index_html_len says {declared_len}",
        path.display(),
        bytes.len()
    );

    (bytes, declared_size)
}

fn scan_uint(text: &str, name: &str) -> usize {
    let idx = text
        .rfind(name)
        .unwrap_or_else(|| panic!("html.h: missing `{name}`"));
    let after_eq = text[idx..]
        .find('=')
        .map(|i| idx + i + 1)
        .unwrap_or_else(|| panic!("html.h: `{name}` has no value"));
    let digits: String = text[after_eq..]
        .chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits
        .parse()
        .unwrap_or_else(|e| panic!("html.h: `{name}` value {digits:?}: {e}"))
}
